In [ ]:
import re 
import numpy as np
from PIL import Image
print("Huffman Compression Program")
print("=================================================================")

Huffman Compression Program


In [ ]:
# taking user input
h = int(input("Enter 1 if you want to input an colour image file, 2 for default gray scale case:"))
if h == 1:
    file = input("Enter the filename:")
    my_string = np.asarray(Image.open(file),np.uint8)
    shape = my_string.shape
    a = my_string
    print ("Enetered string is:",my_string)
    my_string = str(my_string.tolist())
elif h == 2:
    array = np.arange(0, 737280, 1, np.uint8)
    my_string = np.reshape(array, (1024, 720))
    print ("Enetered string is:",my_string)
    a = my_string
    my_string = str(my_string.tolist())

else:
    print("You entered invalid input")   
#frequency of each letter repetition
letters = []
only_letters = []
for letter in my_string:
    if letter not in letters:
        frequency = my_string.count(letter)             
        letters.append(frequency)
        letters.append(letter)
        only_letters.append(letter)

Enter 1 if you want to input an colour image file, 2 for default gray scale case:1
Enter the filename:deepak.jpeg
Enetered string is: [[[ 32  24  21]
  [ 10   2   0]
  [ 30  22  20]
  ...
  [ 24  15  16]
  [ 11   2   3]
  [ 25  17  15]]

 [[ 10   2   0]
  [  7   0   0]
  [ 54  46  44]
  ...
  [ 49  40  41]
  [  6   0   0]
  [ 13   5   3]]

 [[ 28  20  18]
  [ 49  41  39]
  [207 199 197]
  ...
  [192 182 183]
  [ 49  39  40]
  [ 23  13  12]]

 ...

 [[ 19  10  15]
  [ 39  30  35]
  [216 205 211]
  ...
  [201 191 190]
  [ 49  41  39]
  [ 19  11   9]]

 [[ 10   1   4]
  [  6   0   0]
  [ 52  43  46]
  ...
  [ 44  34  33]
  [  6   0   0]
  [  6   0   0]]

 [[ 19  10  11]
  [ 11   2   3]
  [ 20  11  12]
  ...
  [ 22  14  12]
  [ 15   7   5]
  [ 18  10   8]]]


In [ ]:
# sorting according to frequency
nodes = []
while len(letters) > 0:
    nodes.append(letters[0:2])
    letters = letters[2:]                              
nodes.sort()

#Make each unique character as a leaf node
huffman_tree = []
huffman_tree.append(nodes)   

In [ ]:
def combine_nodes(nodes):
    pos = 0
    newnode = []
    if len(nodes) > 1:
        nodes.sort()
        # assigning values 1 and 0
        nodes[pos].append("1")                       
        nodes[pos+1].append("0")
        # combining the nodes to generate pathways
        combined_node1 = (nodes[pos] [0] + nodes[pos+1] [0])
        combined_node2 = (nodes[pos] [1] + nodes[pos+1] [1])  
        newnode.append(combined_node1)
        newnode.append(combined_node2)
        newnodes=[]
        newnodes.append(newnode)
        newnodes = newnodes + nodes[2:]
        nodes = newnodes
        huffman_tree.append(nodes)
        combine_nodes(nodes)
    return huffman_tree       

In [ ]:
# huffman tree generation
newnodes = combine_nodes(nodes)

huffman_tree.sort(reverse = True)
print("Huffman tree with merged pathways:")

checklist = []
for level in huffman_tree:
    for node in level:
        if node not in checklist:
            checklist.append(node)
        else:
            level.remove(node)
count = 0
for level in huffman_tree:
    print("Level", count,":",level)             #print huffman tree
    count+=1
print()

letter_binary = []
if len(only_letters) == 1:
    lettercode = [only_letters[0], "0"]
    letter_binary.append(letter_code*len(my_string))
else:
    for letter in only_letters:
        code =""
        for node in checklist:
            if len (node)>2 and letter in node[1]:           #genrating binary code
                code = code + node[2]
        lettercode =[letter,code]
        letter_binary.append(lettercode)
print(letter_binary)
print("Binary code generated:")
for letter in letter_binary:
    print(letter[0], letter[1])

Huffman tree with merged pathways:
Level 0 : [[2507582, '28049671[]53 ,']]
Level 1 : [[970497, '28049671', '1'], [1537085, '[]53 ,', '0']]
Level 2 : [[629887, '[]53', '1'], [907198, ' ,', '0']]
Level 3 : [[459510, '2', '1'], [510987, '8049671', '0'], [907198, ' ,', '0']]
Level 4 : [[453599, ' ', '1'], [453599, ',', '0'], [510987, '8049671', '0']]
Level 5 : [[303242, '[]', '1'], [326645, '53', '0'], [453599, ',', '0'], [510987, '8049671', '0']]
Level 6 : [[233239, '804', '1'], [277748, '9671', '0'], [326645, '53', '0'], [453599, ',', '0']]
Level 7 : [[162314, '5', '1'], [164331, '3', '0'], [277748, '9671', '0'], [453599, ' ', '1'], [459510, '2', '1']]
Level 8 : [[151621, '[', '1'], [151621, ']', '0'], [164331, '3', '0'], [277748, '9671', '0'], [453599, ',', '0']]
Level 9 : [[136499, '967', '1'], [141249, '1', '0'], [151621, ']', '0'], [164331, '3', '0'], [453599, ' ', '1'], [459510, '2', '1']]
Level 10 : [[103441, '80', '1'], [129798, '4', '0'], [141249, '1', '0'], [151621, ']', '0'], [

In [ ]:
# binary code generated
bitstring =""
for character in my_string:
    for item in letter_binary:
        if character in item:
            bitstring = bitstring + item[1]
binary ="0b"+bitstring
print("Your message as binary is:")
uncompressed_file_size = len(my_string)*7
compressed_file_size = len(binary)-2
print("Your original file size was", uncompressed_file_size,"bits. The compressed size is:",compressed_file_size)
print("This is a saving of ",uncompressed_file_size-compressed_file_size,"bits")
output = open("uncompressed.txt",'w+')
print("unCompressed file generated as uncompressed.txt")
output = open("uncompressed.txt",'w+')
print("Decoding.......")
output.write(bitstring)

Your message as binary is:
Your original file size was 17553074 bits. The compressed size is: 8527464
This is a saving of  9025610 bits
unCompressed file generated as uncompressed.txt
Decoding.......


8527464

In [ ]:
bitstring = str(binary[2:])
compressed_string =""
code =""
for digit in bitstring:
    code = code+digit
    pos=0                                        #iterating and decoding
    for letter in letter_binary:
        if code ==letter[1]:
            compressed_string=compressed_string+letter_binary[pos] [0]
            code=""
        pos+=1



In [ ]:
print("Your COMPRESSED data is:")
if h == 1:
    temp = re.findall(r'\d+', compressed_string)
    res = list(map(int, temp))
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, shape)
    print(res)
    print("Observe the shapes and input and output arrays are matching or not")
    print("Input image dimensions:",shape)
    print("Output image dimensions:",res.shape)
    data = Image.fromarray(res)
    data.save('compressed.jpeg')
    if a.all() == res.all():
        print("Success")
if h == 2:
    temp = re.findall(r'\d+', compressed_string)
    res = list(map(int, temp))
    print(res)
    res = np.array(res)
    res = res.astype(np.uint8)
    res = np.reshape(res, (420,340))
    print(res)
    data = Image.fromarray(res)
    data.save('compressed.jpeg')
    print("Success")

Your COMPRESSED data is:
[[[ 32  24  21]
  [ 10   2   0]
  [ 30  22  20]
  ...
  [ 24  15  16]
  [ 11   2   3]
  [ 25  17  15]]

 [[ 10   2   0]
  [  7   0   0]
  [ 54  46  44]
  ...
  [ 49  40  41]
  [  6   0   0]
  [ 13   5   3]]

 [[ 28  20  18]
  [ 49  41  39]
  [207 199 197]
  ...
  [192 182 183]
  [ 49  39  40]
  [ 23  13  12]]

 ...

 [[ 19  10  15]
  [ 39  30  35]
  [216 205 211]
  ...
  [201 191 190]
  [ 49  41  39]
  [ 19  11   9]]

 [[ 10   1   4]
  [  6   0   0]
  [ 52  43  46]
  ...
  [ 44  34  33]
  [  6   0   0]
  [  6   0   0]]

 [[ 19  10  11]
  [ 11   2   3]
  [ 20  11  12]
  ...
  [ 22  14  12]
  [ 15   7   5]
  [ 18  10   8]]]
Observe the shapes and input and output arrays are matching or not
Input image dimensions: (420, 360, 3)
Output image dimensions: (420, 360, 3)
Success
